### ISSUE TITLE
enhancement: add column with file path (or maybe just name of crate)

### ISSUE THREAD

**Issue by pnkfelix** [oli-obk/fixmeh#1]
this service is great

but I find I have to mouse-over the links in order to get enough context to know if its in a part of the code I'd be comfortable diving into.

Such information could be presented more directly via a separate column in the table.

**Comment by oli-obk** [comment]
The column with the direct link to the code now shows which file you'll end up in (trimmed to hide useless things like the `src` dir or `lib` prefixes or the `.rs` file extension)

**Comment by pnkfelix** [comment]
great!
